# base
map: null
max_episode_steps: 3000
obs_dim: 275  # 270 (lidar) + 3 (velocities) + 2 (frenet frame)
action_dim: 2
show_centerline: True

# env configs
timestep: 0.025
min_speed: 0.5
max_speed: 3.0
max_steer: 0.44 #0.44     # calibration
control_input: ["speed", "steering_angle"]
observation_config: {"type": "original"}
reset_config: {"type": "cl_random_static"}

# etc
num_agents: 1
ego_idx: 0